export const FETCH_ALL_STAFF_REQUEST = 'FETCH_ALL_STAFF_REQUEST';
export const FETCH_ALL_STAFF_SUCCESS = 'FETCH_ALL_STAFF_SUCCESS';
export const FETCH_ALL_STAFF_FAILURE = 'FETCH_ALL_STAFF_FAILURE';


