export const FETCH_ALL_STAFF_REQUEST = 'FETCH_ALL_STAFF_REQUEST';
export const FETCH_ALL_STAFF_SUCCESS = 'FETCH_ALL_STAFF_SUCCESS';
export const FETCH_ALL_STAFF_FAILURE = 'FETCH_ALL_STAFF_FAILURE';

export const ADD_NEW_STAFF_REQUEST = 'ADD_NEW_STAFF_REQUEST';
export const ADD_NEW_STAFF_SUCCESS = 'ADD_NEW_STAFF_SUCCESS';
export const ADD_NEW_STAFF_FAILURE = 'ADD_NEW_STAFF_FAILURE';

export const UPDATE_STAFF_REQUEST = 'UPDATE_STAFF_REQUEST';
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_FAILURE = 'UPDATE_STAFF_FAILURE';

export const CLOCK_STAFF_IN_REQUEST = 'CLOCK_STAFF_IN_REQUEST';
export const CLOCK_STAFF_IN_SUCCESS = 'CLOCK_STAFF_IN_SUCCESS';
export const CLOCK_STAFF_IN_FAILURE = 'CLOCK_STAFF_IN_FAILURE';

export const CLOCK_STAFF_OUT_REQUEST = 'CLOCK_STAFF_OUT_REQUEST';
export const CLOCK_STAFF_OUT_SUCCESS = 'CLOCK_STAFF_OUT_SUCCESS';
export const CLOCK_STAFF_OUT_FAILURE = 'CLOCK_STAFF_OUT_FAILURE';
